
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module movingobjects(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// IR //////////
	input 		          		IRDA_RXD,
	output		          		IRDA_TXD,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


top a(

	.fire_mode1(SW[9]),

	.ShootingModeSw(SW[9]),
	.clk_50MHz(CLOCK_50),
	.red(VGA_R),
	.blue(VGA_B),
	.green(VGA_G),	
	.hsync(VGA_HS),
	.vsync(VGA_VS),
	.clk25(VGA_CLK),
	.blank(VGA_BLANK_N),
	.sync(VGA_SYNC_N),
	.ciguli(~KEY[0]),
	.but1_top(~KEY[1]),
	.but2_top(~KEY[2]),
	.ates_tusu(~KEY[3]),
	.ledverisi(LEDR[3:0]),
	.reset(SW[0]),
	.gamelevel_top(SW[8]),
	.hex0_top(HEX0),.hex1_top(HEX1),.hex2_top(HEX2),.hex3_top(HEX3)
	 );

//=======================================================
//  Structural coding
//=======================================================



endmodule
